### ISSUE TITLE
Getting info about markers in selected cluster

### ISSUE THREAD

**Issue by darknba** [venits/react-native-map-clustering#111]
How to get marker information on the selected cluster?
The following function is returning undefined for markers

` onClusterPress={(coordinates, markers) => {
            console.warn(markers);
            this.animate(coordinates);
          }}>
`

**Comment by venits** [comment]
Hi @darknba 

I released new version of this library.

In new version **onClusterPress()** works like this:

```js
onClusterPress={(cluster, markers) => {console.warn(cluster, markers);}}
``

Right now by default onClusterPress will animate into cluster, so you don't even need this code anymore ;)

**Comment by adrienthiery** [comment]
Hi @venits ,

Nice job on the newest version !

I have a problem with `onClusterPress`, though. I still don't get any markers...

Any lead on why this could happen ? 

I got : 

```
import MapView from 'react-native-map-clustering';
import { Marker, PROVIDER_GOOGLE } from 'react-native-maps';

....

<MapView
    mapRef={this.createMapRef}
    provider={PROVIDER_GOOGLE}
    region={fixed ? initialRegion : null}
    initialRegion={initialRegion}
    style={styles.mapContainer}
    onRegionChangeComplete={this.handleOnRegionChangeFinish}
    onPress={this.handleMapPress}
    onMapReady={this.handleOnMapReady}
    moveOnMarkerPress={false}
    showsUserLocation
    showsMyLocationButton
    clusterTextColor={colors.white}
    clusterTextSize={15}
    clusteringEnabled
    clusterColor={colors.orange}
    clusterBorderColor={colors.white}
    customMapStyle={mapStyle}
    onClusterPress={this.handleClusterPress}
    zoomEnabled
    rotateEnabled
    scrollEnabled
    preserveClusterPressBehavior
    radius={20}
>
    {this.props.points.map((point) => {
        if (!(point.latitude && point.longitude)) {
            return null;
        }

        return (
            <Marker
                point={point}
                key={point.type ? `map-${point.type}-${point.id}` : `map-${point.id}`}
                pinColor={colors.primary}
                style={[
                    styles.marker,
                    this.getMarkerStyle(point),
                ]}
                cluster={point.type !== 'ecocentre'}
                elevation={2}
                image={this.getMarkerImage(point)}
                coordinate={{
                    latitude: Number(point.latitude),
                    longitude: Number(point.longitude),
                }}
                anchor={{
                    x: 0.5,
                    y: 0.5,
                }}
                onPress={this.createMarkerPressHandler(
                    point,
                    'Press'
                )}
            />
        );
    }).filter((item) => item !== null)
    }
</MapView>
```

**Comment by venits** [comment]
@adrienthiery 

Can you show me how `this.handleClusterPress` look like?

I believe you are missing second parameter there gives info about markers:

Here is how this method works:
```js
onClusterPress={(cluster, markers) => console.warn(cluster, markers)}
```

**Comment by adrienthiery** [comment]
`handleClusterPress` looks like this.

```
handleClusterPress = (cluster, markers) => {
        console.log(markers);
        // Still no markers... :/ see https://github.com/venits/react-native-map-clustering/issues/111

        if (markers && markers.length > 0) {
            this.props.navigation.push('MorePoints', {
                points: markers.map((marker) => marker.item.props.point),
                fromProduct: false,
                onlyType: 'List',
            });
        }
    };
```

**Comment by venits** [comment]
@adrienthiery 

Hmm your code should work ;/

Can you check this minimal example:

```js
import React from "react";
import MapView from "react-native-map-clustering";
import { Marker } from "react-native-maps";

const INITIAL_REGION = {
  latitude: 52.5,
  longitude: 19.2,
  latitudeDelta: 8,
  longitudeDelta: 8
};

const App = () => (
  <MapView
    onClusterPress={(cluster, markers) => console.warn(markers)}
    initialRegion={INITIAL_REGION}
    style={{ flex: 1 }}
  >
    <Marker coordinate={{ latitude: 52.0, longitude: 18.2 }} />
    <Marker coordinate={{ latitude: 52.2, longitude: 18.3 }} />
  </MapView>
);

export default App;
```

We should start debugging from simplest example.

**Comment by adrienthiery** [comment]
Ok, so I figured out that the culprit is the `cluster` prop on the markers ... 

As soon as it is on at least one of the markers, the array is empty.

Without it, it works again.

Thanks for your support @venits ! 🙂
