### ISSUE TITLE
After expanding cluster and markers disappears

### ISSUE THREAD

**Issue by Anytram** [venits/react-native-map-clustering#129]
My another problem is that (when I use default cluster look) after running application, clusters and unclustered markers are shown normally. But when I click cluster and expands it disappears with all clustered markers. When I zoomed out cluster shows up again.
I discovered thet when I click my custom button(that sets region with useState hook using geolocation) clustering work perfectly.

**Comment by venits** [comment]
Default behaviour is to zoom cluster after press close enough that user will see all markers that are inside. You can use `preserveClusterPressBehavior={false}` prop to prevent this behaviour.

Nevertheless your markers shouldn't disappear. Can you send me some example code so I can test it?

**Comment by Anytram** [comment]
I figure out when my problem came from. I have custom marker with user location and it is not reneder till user click button. In MapView I had this marker on first, and next were ordinary markers. I just swich this code - first are oridinary markers and then location marker. I don't know why but it works now :D

**Comment by kperreau** [comment]
Same problem for me. Tryed with and without custom marker.
For exemple, i have a cluster of 3 marker in a specific place and when i click to zoom, no marker is visible.

**Map exemple:**
`      <MapView
        initialRegion={{
          latitude: 35,
          longitude: 10,
          latitudeDelta: 75,
          longitudeDelta: 75
        }}
        mapRef={ref => {
          refMap.current = ref;
        }}
        mapType="hybrid"
        provider={PROVIDER_GOOGLE} // remove if not using Google Maps
        style={styles.map}
        showsUserLocation={true}
        onMapReady={() => {
          PermissionsAndroid.request(
            PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION
          ).then(() => {
            setMapReady(true);
          });
        }}
        onLayout={() => {
          setMapLayout(true);
        }}
        clusterColor={platform.brandDark}
      >
        {mapReady && mapLayout && props.photos && (
          generateMarkers()
        )}
      </MapView>`

`generateMarkers()` is a function that generate marker with a map().

**Marker exemple:**
`    <Marker
      title={props.item.userName}
      identifier={props.item.id}
      key={props.item.id}
      tracksViewChanges={!loaded}
      coordinate={{
        latitude: props.item.location._latitude,
        longitude: props.item.location._longitude
      }}
    >`

**Comment by kperreau** [comment]
Fixed in this PR: https://github.com/venits/react-native-map-clustering/pull/146

**Comment by delifaxo** [comment]
> Fixed in this PR: #146
partially helped for me, some markers also disappear =(

**Comment by mchemweno** [comment]
i have the same issue

**Comment by vpwhitefox46** [comment]
Fixed in this PR: #146

**Comment by GunnarAK** [comment]
I have done some research of my own regarding the disappearing of markers with PR #146 
Unfortunately it makes things worse for me. My comment: https://github.com/venits/react-native-map-clustering/pull/146#issuecomment-622406085

**Comment by venits** [comment]
I released a new version of this module: `3.2.0`. I made some changes so it should work now.
Please update module and let me know if that works for you.

**Comment by pdugan20** [comment]
I'm still seeing markers disappear at random with 3.3.7. Usually see it happen after an animateCamera(), but also see it when zooming in or out. Doesn't happen when using the stock MapView from react-native-maps.
