### ISSUE TITLE
Markers disappearing on re-render of MapView

### ISSUE THREAD

**Issue by bobdepreziz** [venits/react-native-map-clustering#202]
Hello,

I have been experimenting a bit after using this package in our project to do the clustering of markers. I saw markers and clusters sometimes disappearing on the map. I investigated the issue and it happens when the map re-renders. I tested this in version 3.4.0 and there you have this bug, I also tested with version 3.3.0 and there it seems to work just fine. Issue #200 might also have to do with this. I added a test project where you can easily test it with, see link at the end of the post.

Repro steps:
 - Run the project, it contains a counter that forces a re-render each second
 - Check the markers on the map
 
Expected:
Markers stay visible and stay in place without flickering

Actual:
Markers disappear 
 

[Link to repo to reproduce on my github](https://github.com/bobdepreziz/MarkerBugRNMapsClustering)

**Comment by irenmax** [comment]
I have the same problem after updating to 3.4.0, it worked fine on the previous version.

**Comment by irenmax** [comment]
I think this behavior is caused by `updateRegion(restProps.region || restProps.initialRegion);` in ClusteredMapView.js. Removing this line fixed it for me with no further problems.

**Comment by venits** [comment]
Hi, @irenmax 

you are right, there was small mistake in this `useEffect()` and `updateRegion` is not needed there for sure :) 

I released new version `3.4.2` that has fix for that. Please let me know if that fixes problem with disappearing markers for you. 
On my side it works fine 👍

**Comment by irenmax** [comment]
Hey @venits, `3.4.2` works fine for me now, thank you! :)

**Comment by AlixH** [comment]
I am still having this issue, when re-redinering, there is a flickering

**Comment by jackimatin** [comment]
same issue

**Comment by andsanmar** [comment]
Hi, after 2 years there is not yet any comment on this. Has anyone been able to solve the flickering?
