### ISSUE TITLE
TypeError: Cannot read property 'range' of undefined

### ISSUE THREAD

**Issue by ghost** [venits/react-native-map-clustering#50]
Way of reproduce (this is not 100% sure):
1. Put some clustered markers on map.
2. Scroll map from west to east for some time (5-10 seconds).
3. The application will throw an exception.

Result:
```
TypeError: Cannot read property 'range' of undefined
This error is located at:
...
at SuperCluster.getClusters (index.js:77)
    at MapWithClustering.calculateClustersForMap (MapWithClustering.js:139)
    at MapWithClustering.proxiedMethod (createPrototypeProxy.js:44)
    at MapWithClustering.createMarkersOnMap (MapWithClustering.js:99)
    at MapWithClustering.proxiedMethod (createPrototypeProxy.js:44)
    at MapWithClustering.componentWillReceiveProps (MapWithClustering.js:34)
    at MapWithClustering.proxiedMethod (createPrototypeProxy.js:44)
```

Conclusion:
It seems the tree object in getClusters method from supercluster is undefined:
```
getClusters: function (bbox, zoom) {
        var tree = this.trees[this._limitZoom(zoom)];
        var ids = tree.range(lngX(bbox[0]), latY(bbox[3]), lngX(bbox[2]), latY(bbox[1]));
        var clusters = [];
        for (var i = 0; i < ids.length; i++) {
            var c = tree.points[ids[i]];
            clusters.push(c.numPoints ? getClusterJSON(c) : this.points[c.id]);
        }
        return clusters;
    },
```

**Comment by DanGDroid** [comment]
i had this problem with another cluster lib,
it happens when crossing the international dateline on react-native-maps on android
see this:
https://github.com/novalabio/react-native-maps-super-cluster/issues/20

**Comment by cinder92** [comment]
same issue here Android 9 pie

**Comment by ballenwillis** [comment]
Same issue here. Why has this not been addressed? Open for a year and a half?

**Comment by venits** [comment]
I released new version of this library. This issue should be solved 🎉

**Comment by iammadanlal** [comment]
@venits I have installed new version but the same error still coming.
TypeError: Cannot read property 'range' of undefined

It worked first and now i have tried multiple times. it showing this error and app crashed. I need help urgently and my app usecase is fit this library as i have to show thousand of markers in map.

**Comment by vinceprofeta** [comment]
@iammadanlal did you find a solution?

**Comment by antoinerousseau** [comment]
same issue here, @venits how did you fix this?

**Comment by antoinerousseau** [comment]
Had the issue on Android because I had `mapType="mutedStandard"`.
Seemed unrelated, but changed it to `mapType={Platform.OS === "ios" ? "mutedStandard" : "standard"}` and it worked.

**Comment by antoinerousseau** [comment]
It can also happen if the initial region does not have valid coordinates.

**Comment by DatIsVinnie** [comment]
Hey guys I ran into the issue that the first time the app runs everything works but when I opent the app for the second time the supercluster library gave me the error `Cannot read property 'range' of undefined`.

<img width="338" alt="afbeelding" src="https://github.com/user-attachments/assets/60b753ab-0218-449e-bbef-480d08d7c173">


Well after a lot of ours of debugging crying and fixing I have found a workaround how to fix this issue see code below

```JS
        <MapView
          ref={this.mapRef}
          style={{ flex: 1 }}
          rotateEnabled={false}
          showsUserLocation={true}
          showsMyLocationButton={false}
          showsTraffic={true}
          initialRegion={initialRegion}
          region={this.cache.get('scheduleListSavedRegion') || initialRegion}
          onRegionChangeComplete={this.saveMapRegion}
          clusterColor="black"
          spiderLineColor="black"
          clusterTextColor="white"
        >
          {markers.map((marker) => (
            <Marker
              key={marker.id}
              coordinate={{
                latitude: marker.latitude,
                longitude: marker.longitude,
              }}
              onPress={() => this.handleMarkerPress(marker)}
            >
              <Image
                source={mapMarker}
                style={{ width: 40, height: 40 }}
              />
            </Marker>
          ))}
        </MapView>
```
and the function to make the array of markers 
        
```JS
const markers = data.map((row, index) => {
    const latitude = parseFloat(row.location_geo_latitude);
    const longitude = parseFloat(row.location_geo_longitude);

    if (!isNaN(latitude) && !isNaN(longitude)) {
        return {
            id: row.grouped_locationid,
            latitude: latitude,
            longitude: longitude,
        };
    }

    return null; // Filter out invalid markers
});
```

I hope I can help someone by sharing this piece of code!
